channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::bismark>=0.24.2
  - bioconda::samtools>=1.21
  - bioconda::hisat2
  - bioconda::bowtie2
  - bioconda::minimap2
  - bioconda::perl-gdgraph
