channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::gatk4>=4.6.1.0
  - bioconda::samtools>=1.22
  - bioconda::vcftools>=0.1.17
  - bioconda::bcftools>=1.22
  - conda-forge::gawk
  - conda-forge::zstd
