channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python=3.7.12
    - pip
    - pip:
      - git+https://bitbucket.org/zyf1997/astair.git
    - bioconda::bwa>=0.7.18
    - bioconda::bwameth>=0.2.7
    - bioconda::samtools>=1.21
    - conda-forge::matplotlib
    - conda-forge::pigz
