input_dir: input

#! this part is used to specify the reference genome file to be used
ref:
  astair:
    D5:
    D6:
    F7:
    M8:
    BC:
    BL:
    HF: /hot_warm_data/ref/quartet/DNA/custom_genome/BL/samtools/BL.fa
    T1:
    T2:
    T3:
    T4:
  bwa-mem:
    D5:
    D6:
    F7:
    M8:
    BC:
    BL:
    HF: /hot_warm_data/ref/quartet/DNA/custom_genome/BL/bwa-mem/BL.fa
    T1:
    T2:
    T3:
    T4:
  bwa-meme:
    D5:
    D6:
    F7:
    M8:
    BC:
    BL:
    HF: /hot_warm_data/ref/quartet/DNA/custom_genome/BL/bwa-meme/BL.fa
    T1:
    T2:
    T3:
    T4:
  bwa-meth:
    D5:
    D6:
    F7:
    M8:
    BC:
    BL:
    HF: /hot_warm_data/ref/quartet/DNA/custom_genome/BL/bwa-meth/BL.fa
    T1:
    T2:
    T3:
    T4:
  bismark-bowtie2:
    D5:
    D6:
    F7:
    M8:
    BC:
    BL:
    HF: /hot_warm_data/ref/quartet/DNA/custom_genome/BL/bismark-bowtie2
    T1:
    T2:
    T3:
    T4:
  bismark-hisat2:
    D5:
    D6:
    F7:
    M8:
    BC:
    BL:
    HF: /hot_warm_data/ref/quartet/DNA/custom_genome/BL/bismark-hisat2
    T1:
    T2:
    T3:
    T4:
  biscuit:
    HF: /hot_warm_data/ref/quartet/DNA/custom_genome/BL/biscuit/BL.fa
  bsgenova:
    HF: /hot_warm_data/ref/quartet/DNA/custom_genome/BL/samtools/BL.fa
  fame:
    HF: /hot_warm_data/ref/quartet/DNA/custom_genome/BL/FAME/BL.fa.index
  msuite2:
    HF: /home/zhangyuanfeng/software/Msuite2_edited/index/BL

astair:
  method:
    BS: CtoT
    EM: CtoT
    RR: CtoT
    PS: mCtoT
  align:
    extra_params:
  count:
    extra_params:
  idbias:
    extra_params:
  mbias:
    extra_params:

biscuit:
  align:
    extra_params:
  pileup:
    extra_params:
  vcf2bed:
    extra_params:
  qc:
    extra_params:
  bsstrand:
    extra_params:
  cinread:
    extra_params:

bsgenova:
  count:
    extra_params:

bismark:
  align_bowtie2:
    extra_params: --strandID
  align_hisat2:
    extra_params: --strandID
  exactor:
    extra_params:
  coverage2cytosine:
    extra_params:
  dedup:
    extra_params:
  bam2nuc:
    extra_params:

bwa-meme:
  extra_params:

bwa-meth:
  extra_params:

falco:
  extra_params:

fame:
  extra_params: --gzip_reads

fastp:
  extra_params:

fastqc:
  extra_params:

gatk:
  cal_bqsr:
    snp_vcf: resources/dbsnp/common.dbsnp.vcf.gz
    extra_params:
  apply_bqsr:
    extra_params:
  analyze_covariates:
    extra_params:
  dedup:
    extra_params:

methyldackel:
  count:
    extra_params:
  mbias:
    extra_params:

msuite2:
  extra_params:

qualimap:
  extra_params: --java-mem-size=80G

samtools:
  fixmate:
    extra_params:
  mkdup:
    extra_params:
  stats:
    extra_params:
  flagstat:
    extra_params:

trim-galore:
  extra_params:
