input_dir: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/eqa/fastq
sample_sheet: config/sample_sheet.csv  # never use absolute path.

#! this part is used to specify the reference genome file to be used
ref:  # `astair align` has been deprecated because it's just calling bwa-mem and it introduces bugs.
  bwa-mem:
    D5: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEM/D5_IC.fa
    D6: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEM/D5_IC.fa
    F7: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/F7_IC/MEM/F7_IC.fa
    M8: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/M8_IC/MEM/M8_IC.fa
    BC: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BC_IC/MEM/BC_IC.fa
    BL: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BL_IC/MEM/BL_IC.fa
    HF: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BL_IC/MEM/BL_IC.fa
    T1: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEM/D5_IC.fa
    T2: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEM/D5_IC.fa
    T3: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEM/D5_IC.fa
    T4: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEM/D5_IC.fa
  bwa-mem2:
    D5: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEM2/D5_IC.fa
    D6: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEM2/D5_IC.fa
    F7: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/F7_IC/MEM2/F7_IC.fa
    M8: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/M8_IC/MEM2/M8_IC.fa
    BC: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BC_IC/MEM2/BC_IC.fa
    BL: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BL_IC/MEM2/BL_IC.fa
    HF: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BL_IC/MEM2/BL_IC.fa
    T1: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEM2/D5_IC.fa
    T2: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEM2/D5_IC.fa
    T3: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEM2/D5_IC.fa
    T4: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEM2/D5_IC.fa
  bwa-meme:
    D5: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEME/D5_IC.fa
    D6: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEME/D5_IC.fa
    F7: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/F7_IC/MEME/F7_IC.fa
    M8: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/M8_IC/MEME/M8_IC.fa
    BC: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BC_IC/MEME/BC_IC.fa
    BL: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BL_IC/MEME/BL_IC.fa
    HF: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BL_IC/MEME/BL_IC.fa
    T1: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEME/D5_IC.fa
    T2: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEME/D5_IC.fa
    T3: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEME/D5_IC.fa
    T4: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/MEME/D5_IC.fa
  bwa-meth:
    D5: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BWA_METH/D5_IC.fa
    D6: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BWA_METH/D5_IC.fa
    F7: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/F7_IC/BWA_METH/F7_IC.fa
    M8: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/M8_IC/BWA_METH/M8_IC.fa
    BC: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BC_IC/BWA_METH/BC_IC.fa
    BL: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BL_IC/BWA_METH/BL_IC.fa
    HF: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BL_IC/BWA_METH/BL_IC.fa
    T1: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BWA_METH/D5_IC.fa
    T2: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BWA_METH/D5_IC.fa
    T3: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BWA_METH/D5_IC.fa
    T4: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BWA_METH/D5_IC.fa
  bismark-bowtie2:
    D5: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BISMARK_BOWTIE2
    D6: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BISMARK_BOWTIE2
    F7: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/F7_IC/BISMARK_BOWTIE2
    M8: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/M8_IC/BISMARK_BOWTIE2
    BC: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BC_IC/BISMARK_BOWTIE2
    BL: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BL_IC/BISMARK_BOWTIE2
    HF: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BL_IC/BISMARK_BOWTIE2
    T1: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BISMARK_BOWTIE2
    T2: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BISMARK_BOWTIE2
    T3: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BISMARK_BOWTIE2
    T4: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BISMARK_BOWTIE2
  bismark-hisat2:
    D5: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BISMARK_HISAT2
    D6: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BISMARK_HISAT2
    F7: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/F7_IC/BISMARK_HISAT2
    M8: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/M8_IC/BISMARK_HISAT2
    BC: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BC_IC/BISMARK_HISAT2
    BL: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BL_IC/BISMARK_HISAT2
    HF: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/BL_IC/BISMARK_HISAT2
    T1: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BISMARK_HISAT2
    T2: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BISMARK_HISAT2
    T3: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BISMARK_HISAT2
    T4: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/gxr_22210700111/custom_genomes/D5_IC/BISMARK_HISAT2

astair:
  method:
    BS: CtoT
    EM: CtoT
    RR: CtoT
    PS: mCtoT
  count:
    extra_params:
  idbias:
    extra_params:
  mbias:
    extra_params:

biscuit:
  align:
    extra_params:
  count:
    extra_params:
  stats:
    extra_params:

bismark:
  align_bowtie2:
    extra_params:
  align_hisat2:
    extra_params:
  exactor:
    extra_params:
  coverage2cytosine:
    extra_params:
  dedup:
    extra_params:
  bam2nuc:
    extra_params:

bwa-meme:
  extra_params:

bwa-meth:
  extra_params:

falco:
  extra_params:

fastp:
  extra_params:

fastqc:
  extra_params:

gatk:
  cal_bqsr:
    snp_vcf: resources/dbsnp/common.dbsnp.vcf.gz
    extra_params:
  apply_bqsr:
    extra_params:
  analyze_covariates:
    extra_params:
  dedup:
    extra_params:

methyldackel:
  count:
    extra_params:
  mbias:
    extra_params:

qualimap:
  extra_params:

samtools:
  fixmate:
    extra_params:
  mkdup:
    extra_params:
  stats:
    extra_params:
  flagstat:
    extra_params:

trim-galore:
  extra_params:
