channels:
    - bioconda
    - conda-forge
dependencies:
    - bioconda::biscuit>=1.6.0.20241216
    - bioconda::mbuffer
    - bioconda::samtools>=1.22
    - bioconda::bedtools>=2.29.1
    - conda-forge::pigz
    - conda-forge::gawk
