channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::samtools>=1.22
  - bioconda::bwa
  - bioconda::seqtk
  - bioconda::seqkit
  - bioconda::mbuffer
  - conda-forge::liblzma
